name: 'CI'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

jobs:
  build: 
    runs-on: ubuntu-latest
    container: node:12-buster
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies 
        run: yarn
      - name: Verify
        run: |
          yarn run build 
          yarn run format
          yarn run lint
      - name: Package
        run: yarn run package

  test: 
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          milliseconds: 1000
